Effectively managing student and graduate records is imperative for ensuring accuracy, accessibility, and security within the educational landscape. Traditional centralized systems often reveal significant limitations, including inefficiencies and vulnerabilities that can compromise data integrity. As such, there is an increasing necessity for innovative digital verification methods. These advancements enhance the reliability of record-keeping and facilitate easier access for stakeholders, thereby fostering a more streamlined and secure educational environment @VerificationofUniversityStudentandGraduateDatausingBlockchainTechnology.

In recent years, the issue of counterfeit diplomas and transcripts has gained considerable attention. In 2019, Nuril Furkan underscored the growing threat of fraudulent academic credentials—especially during general elections—emphasizing the urgent need for stringent verification processes @ElectronicDocumentAuthenticityVerificationofDiplomaAndTranscriptUsingSmartContractonEthereumBlockchain. Proactively addressing this issue allows universities to safeguard their academic integrity, enhance student learning experiences, and foster a culture of trust.

The InterPlanetary File System significantly boosts the safety and accessibility of digital credentials by utilizing decentralized storage, ensuring that sensitive information is protected while remaining easily accessible to authorized users, as shown in @ipfs. Improving data integrity involves reducing vulnerabilities within centralized systems and carefully controlling access, ensuring that sensitive information remains secure and trustworthy for all users @SecureFileSharingUsingBlockchainandIPFSwithSmartContract-BasedAccessControl.

#figure(
  image("img/ipfs.png", width: 90%),
  caption: [IPFS Distributed Network],
)<ipfs>

Blockchain technology establishes a decentralized framework that guarantees the integrity and immutability of data by employing robust cryptographic techniques. This ensures secure transactions and fosters trust among participants in various digital ecosystems @BlockchainInEducationASystematicReviewAndPracticalCaseStudies.

Blockchain technology and InterPlanetary File System (IPFS) provide a robust framework for decentralized and secure solutions, ensuring that certificate verification is robust and trustworthy, enhancing transparency and reliability for all users. IPFS provides a way to store data in a decentralized manner @9903549. It brings promise and difficulty for the systems that will come after it. This innovative approach ensures enhanced security and decentralization, empowering users with greater control over their credentials. By leveraging both technologies' strengths, the system aims to facilitate a seamless and user-friendly experience, thereby revolutionizing the landscape of credential verification processes.

Blockchain has evolved beyond cryptocurrencies, enabling innovative solutions in various industries and enhancing transparency and trust. This technology is applicable across various sectors, including supply chain management and healthcare, due to its inherent capabilities in secure data storage and management @AnOverviewoftheEmergingTechnologyBlockchain. This versatility positions blockchain as an ideal solution for applications demanding high levels of trust and transparency.

To further improve this system, the implementation of smart contracts is essential. Smart contracts enable automated, trustless transactions, ensuring that diploma verification is both tamper-proof and efficient. Utilizing Proof of History (PoH) as the consensus mechanism within the Solana blockchain guarantees fast and secure transaction processing, supporting real-time verification without sacrificing security.

In Indonesia, the online diploma verification system (Sistem Verifikasi Ijazah Secara Elektronik) or SIVIL was implemented in 2017 to address the ongoing problem of fraudulent diplomas and transcripts @ElectronicDocumentAuthenticityVerificationofDiplomaAndTranscriptUsingSmartContractonEthereumBlockchain. A primary concern is the risk of technological obsolescence and security vulnerabilities linked to centralized systems @JudhiePutra.2024. Without continual updates and strong cyber defenses, the verification system risks becoming vulnerable to vulnerabilities, which could jeopardize the legitimacy of complying graduates. Moreover, Indonesia's bureaucratic educational governance may obstruct the rapid adoption of blockchain technology and the extensive reforms necessary for effective SIVIL implementation @Rehman.2025.

Recent implementations of blockchain-based verification systems, such those by Kanan et al. at Al-Zaytoonah University and by Cheng et al., illustrate the capability of this technology to enhance and secure academic credentialing, thereby mitigating the vulnerabilities of the SIVIL system. These innovative approaches reduce fraud risks and enhance trust in educational qualifications, offering a promising path forward for institutions globally @8717505 @8394455.

You may be questioning the rationale for selecting a public blockchain over a private one. The allure of a private blockchain is compelling, particularly for enterprises pursuing rapidity and efficacy. The reduction in participants can enhance transaction speed @Yang2020Public. However, the drawback is that private blockchains exhibit greater centralization, being governed by a singular corporation or a consortium of entities @Strehle2020Public. Although this may yield certain efficiencies, it concurrently presents concerns such as censorship, diminished openness, and eroded confidence.

Public blockchains, with their decentralized and transparent nature, offer a trust-centric system where transactions are publicly recorded, visible, and verifiable by anyone @Kabashi.2024. This allows, for instance, easy authentication of a student's diploma by an employer via a public address, providing definitive, immutable, and universally available information. Their global accessibility is a significant advantage for applications like academic credentialing, enabling worldwide access without centralized verification. This study aims to evaluate a system for keeping and certifying academic credentials in a testnet environment, assessing its scalability, security, and efficacy to foster a more transparent, efficient, and secure diploma verification process.
