Effectively managing student and graduate records is imperative for ensuring accuracy, accessibility, and security within the educational landscape. Traditional centralized systems often reveal significant limitations, including inefficiencies and vulnerabilities that can compromise data integrity. As such, there is an increasing necessity for innovative digital verification methods. These advancements enhance the reliability of record-keeping and facilitate easier access for stakeholders, thereby fostering a more streamlined and secure educational environment @VerificationofUniversityStudentandGraduateDatausingBlockchainTechnology.

In recent years, the issue of counterfeit diplomas and transcripts has gained considerable attention. In 2019, Nuril Furkan underscored the growing threat of fraudulent academic credentials—especially during general elections—emphasizing the urgent need for stringent verification processes @ElectronicDocumentAuthenticityVerificationofDiplomaAndTranscriptUsingSmartContractonEthereumBlockchain. Proactively addressing this issue allows universities to safeguard their academic integrity, enhance student learning experiences, and foster a culture of trust.

The InterPlanetary File System significantly boosts the safety and accessibility of digital credentials by utilizing decentralized storage, ensuring that sensitive information is protected while remaining easily accessible to authorized users, as shown in @ipfs. Improving data integrity involves reducing vulnerabilities within centralized systems and carefully controlling access, ensuring that sensitive information remains secure and trustworthy for all users @SecureFileSharingUsingBlockchainandIPFSwithSmartContract-BasedAccessControl.

#figure(
  image("img/ipfs.png", width: 80%),
  caption: [IPFS Distributed Network],
)<ipfs>

Blockchain technology establishes a decentralized framework that guarantees the integrity and immutability of data by employing robust cryptographic techniques. This ensures secure transactions and fosters trust among participants in various digital ecosystems @BlockchainInEducationASystematicReviewAndPracticalCaseStudies.

Blockchain technology and InterPlanetary File System (IPFS) provide a robust framework for decentralized and secure solutions, ensuring that certificate verification is robust and trustworthy, enhancing transparency and reliability for all users. IPFS provides a way to store data in a decentralized manner @9903549. It brings promise and difficulty for the systems that will come after it. This innovative approach ensures enhanced security and decentralization, empowering users with greater control over their credentials. By leveraging both technologies' strengths, the system aims to facilitate a seamless and user-friendly experience, thereby revolutionizing the landscape of credential verification processes.

Blockchain has evolved beyond cryptocurrencies, enabling innovative solutions in various industries and enhancing transparency and trust. This technology is applicable across various sectors, including supply chain management and healthcare, due to its inherent capabilities in secure data storage and management @AnOverviewoftheEmergingTechnologyBlockchain. This versatility positions blockchain as an ideal solution for applications demanding high levels of trust and transparency.

To further improve this system, the implementation of smart contracts is essential. Smart contracts enable automated, trustless transactions, ensuring that diploma verification is both tamper-proof and efficient. Utilizing Proof of History (PoH) as the consensus mechanism within the Solana blockchain guarantees fast and secure transaction processing, supporting real-time verification without sacrificing security.

In Indonesia, the online diploma verification system SIVIL was introduced in 2017 to combat the persistent issue of counterfeit diplomas and transcripts @ElectronicDocumentAuthenticityVerificationofDiplomaAndTranscriptUsingSmartContractonEthereumBlockchain. Despite these efforts, challenges remain, underscoring the need for continuous improvements in verification processes and greater public awareness regarding the authenticity of academic records.

Recent implementations of blockchain-based verification systems—such as those by Kanan et al. at Al-Zaytoonah University and by Cheng et al.—demonstrate the potential of this technology to streamline and secure academic credentialing. These innovative approaches reduce fraud risks and enhance trust in educational qualifications, offering a promising path forward for institutions globally @8717505 @8394455.

You may be questioning the rationale for selecting a public blockchain over a private one. The allure of a private blockchain is compelling, particularly for enterprises pursuing rapidity and efficacy. The reduction in participants can enhance transaction speed @Yang2020Public. However, the drawback is that private blockchains exhibit greater centralization, being governed by a singular corporation or a consortium of entities @Strehle2020Public. Although this may yield certain efficiencies, it concurrently presents concerns such as censorship, diminished openness, and eroded confidence.

In contrast, public blockchains, owing to their decentralized nature, offer a unique set of benefits. Consider a public blockchain as a comprehensive ledger where each transaction is recorded, visible, and verified by any interested individual. This creates a trust-centric system. For example, if a student wishes to authenticate their diploma to a potential employer, they can easily furnish a public address, allowing the company to check it immediately without needing to contact the university. The information is definitive, immutable, and available to everybody.

Furthermore, public blockchains offer global accessibility. Individuals, irrespective of their location, can access and interact with the data. This signifies a significant advancement for applications such as academic credentialing, where students, companies, and institutions often span many geographic locations. Public blockchains make these credentials globally accessible, obviating the need for centralized authorization or verification.

This study seeks to evaluate the system in a testnet setting as a proof of concept, assessing its scalability, security, and efficacy in keeping and certifying academic credentials. The effective execution of this system will facilitate a more transparent, efficient, and secure diploma verification process.
