Effectively managing and securing students and graduates records accurately in the context of education streamlined accessibility poses a challenge. The traditional centralized methods of storing data always face limitations because of their inefficient nature. This is a reason for adopting new digital verification systems which innovative technologies develop. Moreover, these enhancements also improve the accessibility of such records to accredited parties within the education sector during their operations @VerificationofUniversityStudentandGraduateDatausingBlockchainTechnology.

The concern regarding counterfeit diplomas and transcripts has sharply risen in the past few years. Furkan Nuril noted in 2019 how phony academic documents were surging, especially during national elections @ElectronicDocumentAuthenticityVerificationofDiplomaAndTranscriptUsingSmartContractonEthereumBlockchain. Addressing this issue proactively helps universities enhance their academic standing, strengthen student learning outcomes, and foster a culture of trust.

InterPlanetary File System (IPFS) increases the security and accessibility of digital credentials through the use of decentralized storage sensitive information is secure but easily accessible to proper users as shown in @ipfs. Data integrity is enhanced due to the limited risk of attack in central systems and the strict management of shared sensitive data for all @SecureFileSharingUsingBlockchainandIPFSwithSmartContract-BasedAccessControl.

#figure(
  image("img/ipfs.png", width: 80%),
  caption: [IPFS Distributed Network],
)<ipfs>

The integrity and immutability of data are secured through robust cryptographic mechanisms in the blockchain system. This fosters secure transactions and encourages trust among participants in multifarious digital ecosystem @BlockchainInEducationASystematicReviewAndPracticalCaseStudies.

Blockchain technology, along with the InterPlanetary File System (IPFS), offers a powerful infrastructure for secure decentralized solutions wherein users can trust certificate validation, ensuring all transactions are trustless and transparent for the users. Decentralized data storage is offered by IPFS @9903549. This poses and guarantees challenges to the succeeding systems. This paradigm guarantees better protection and greater control for users over their credentials, achieving decentralization and security. The system seeks to streamline user experience by integrating the advantages from both technologies, which in turn, transforms the atmosphere for credential verification.

The utilization of blockchain technology has moved beyond only utilizing it in cryptocurrencies, to enabling new use cases in different sectors to increase transparency and trust. Its most distinct impact can be witnessed in healthcare and even in the management of supply chains, showing its cross-industry adaptability where data can be securely stored and managed @AnOverviewoftheEmergingTechnologyBlockchain. Hence, its great extensibility makes it easier to use the blockchain to maintain high levels of transparency and high degrees of trust.

To advance the effectiveness of the system, incorporating automated processes using smart contracts is necessary. Trustless transactions through automation provided by smart contracts uphold integrity in automation for diploma verification, rendering it both irreversible tampering and automated in nature. Employing Proof of History (PoH) as the consensus mechanism on the Solana blockchain ensures swift, secure processing of transactions which enables real-time verification with maintained security.

The history of counterfeit academic diplomas and transcripts has existed for decades, but Indonesia took a step forward in 2017 with the implementation of the electronic diploma verification system, Sistem Verifikasi Ijazah Secara Elektronik/SIVIL @ElectronicDocumentAuthenticityVerificationofDiplomaAndTranscriptUsingSmartContractonEthereumBlockchain as shown in @sivil. Centralized systems pose a major risk of technological stagnation, obsolescence, or even lapse in security @JudhiePutra.2024. In the absence of strong cybersecurity measures, frequent updates and robust cybersecurity frameworks, the verification systems are susceptible to weaknesses that undermine the integrity of graduate verification downstream. The centralized system suffers from what is referred to as bureaucratic educational administration which is the constraining acceleration of positional obfuscation in governance systems which slows the advancement of blockchain technology alongside other necessary paradigm-shifting SIVIL reforms @Rehman.2025.

#figure(
  image("img/sivil.png", width: 80%),
  caption: [SIVIL System],
)<sivil>

The works of Kanan et al. from Al-Zaytoonah University and Cheng et al. illustrate how blockchain-based authentication systems can more effectively and securely transform academic credentialing, thereby addressing the shortcomings of the SIVIL system. These modern methodologies mitigate the susceptibility to fraudulent credentialing while significantly bolstering trust in qualifications, thereby paving the way towards a more promising future for all institutions @8717505 @8394455.

You may be wondering why anyone would opt for a public blockchain over its private counterpart. A private blockchain carries its appeal, especially for businesses that need speed and efficiency. The reduction in participants can accelerate transaction time @Yang2020Public. However, a drawback is that private blockchains are more centralized and controlled by one firm or a consortium of firms @Strehle2020Public. While these factors may provide some efficiency, they also bring about issues of censorship, reduced transparency, and trust.

The trust model utilized by public blockchains is entirely based on a decentralized system where transactions are recorded chronologically and verifiable by all @Kabashi.2024. This enables an employer to verify a student’s diploma by accessing him or her directly, thus providing unquestionable، unalterable data. Because they are borderless, they greatly benefit credentialing in education by allowing unrestricted global access without the need for centralized verification. This study seeks to validate a system for storing and verifying diplomas in a testnet environment in order to examine its scalability, security, and efficacy in achieving a more transparent, efficient, and secure diploma verification process.
