This chapter provides a comprehensive overview of the foundational technologies that support decentralized degree verification systems. It examines blockchain’s immutable ledger capabilities, the decentralized storage mechanism of the InterPlanetary File System (IPFS), and the interoperability of the Binance Smart Chain (BSC) network.

Blockchain technology represents a revolutionary advancement in data management by utilizing a distributed ledger system that guarantees secure, immutable, and transparent data storage across a decentralized network @Beck2017Blockchain. This paradigm shift is characterized by its fundamental features: immutability, transparency, and decentralization, features that collectively uphold data integrity while eliminating the need for centralized intermediaries. Once information is recorded on a blockchain, it becomes resistant to unauthorized alterations—a crucial safeguard that reduces the likelihood of credential fraud, particularly in academic contexts @Beck2017Blockchain. 

The immutable nature of blockchain ensures that once a credential is validated and added to the ledger, it cannot be altered or deleted, thereby preserving its authenticity over time @Rahardja2021Immutable. Additionally, the transparent framework of blockchain enables various stakeholders, such as employers and educational institutions, to independently verify the accuracy of academic qualifications. This independence not only enhances trust but also streamlines the verification process, fostering a more efficient system of credentialing that benefits both job seekers and hiring organizations.

In the realm of decentralized diploma verification, the InterPlanetary File System (IPFS) is preferred over conventional cloud platforms, such as Amazon Web Services (AWS) or Google Cloud Platform (GCP), because it adheres to the foundational principles of decentralization and trustless systems. In contrast to centralized cloud service providers that retain authority over data storage and access, IPFS offers a more distributed and autonomous approach to data management.

IPFS is a peer-to-peer distributed file system that allows data to be stored and accessed in a decentralized manner, overcoming the drawbacks of centralized systems such as single points of failure and arbitrary control @Politou2020Delegated. Pinata is a service that facilitates the use of IPFS by providing an easier interface to upload and manage data in IPFS @Vaidya2024Blockchain-Powered. The implemented system utilizes the InterPlanetary File System (IPFS) protocol to securely upload users’ academic degrees, which are subsequently stored via the Pinata platform.

A significant advantage of the InterPlanetary File System (IPFS) is its implementation of content-addressable storage, whereby each file is designated by a unique cryptographic hash @Doan2022Toward. This mechanism offers a reliable guarantee of data integrity, as any alteration to the file will result in a distinct hash value, thus facilitating the immediate detection of any tampering. In contrast, centralized platforms employ location-based addressing for data storage, a strategy that does not inherently validate the authenticity of the content.

