This chapter provides a comprehensive overview of the foundational technologies that support decentralized degree verification systems. It examines blockchain’s immutable ledger capabilities, the decentralized storage mechanism of the InterPlanetary File System (IPFS), and the interoperability of the Binance Smart Chain (BSC) network.

Blockchain technology represents a revolutionary advancement in data management by utilizing a distributed ledger system that guarantees secure, immutable, and transparent data storage across a decentralized network @Beck2017Blockchain. This paradigm shift is characterized by its fundamental features: immutability, transparency, and decentralization, features that collectively uphold data integrity while eliminating the need for centralized intermediaries. Once information is recorded on a blockchain, it becomes resistant to unauthorized alterations—a crucial safeguard that reduces the likelihood of credential fraud, particularly in academic contexts @Beck2017Blockchain. 

The immutable nature of blockchain ensures that once a credential is validated and added to the ledger, it cannot be altered or deleted, thereby preserving its authenticity over time @Rahardja2021Immutable. Additionally, the transparent framework of blockchain enables various stakeholders, such as employers and educational institutions, to independently verify the accuracy of academic qualifications. This independence not only enhances trust but also streamlines the verification process, fostering a more efficient system of credentialing that benefits both job seekers and hiring organizations.

In the realm of decentralized diploma verification, the InterPlanetary File System (IPFS) is preferred over conventional cloud platforms, such as Amazon Web Services (AWS) or Google Cloud Platform (GCP), because it adheres to the foundational principles of decentralization and trustless systems. In contrast to centralized cloud service providers that retain authority over data storage and access, IPFS offers a more distributed and autonomous approach to data management.

IPFS is a peer-to-peer distributed file system that allows data to be stored and accessed in a decentralized manner, overcoming the drawbacks of centralized systems such as single points of failure and arbitrary control @Politou2020Delegated. Pinata is a service that facilitates the use of IPFS by providing an easier interface to upload and manage data in IPFS @Vaidya2024Blockchain-Powered. The implemented system utilizes the InterPlanetary File System (IPFS) protocol to securely upload users’ academic degrees, which are subsequently stored via the Pinata platform.

A significant advantage of the InterPlanetary File System (IPFS) is its implementation of content-addressable storage, whereby each file is designated by a unique cryptographic hash @Doan2022Toward. This mechanism offers a reliable guarantee of data integrity, as any alteration to the file will result in a distinct hash value, thus facilitating the immediate detection of any tampering. In contrast, centralized platforms employ location-based addressing for data storage, a strategy that does not inherently validate the authenticity of the content.

Binance Smart Chain (BSC) is a blockchain infrastructure specifically engineered to facilitate the creation of decentralized applications (DApps), prioritizing high transaction throughput and minimal transaction costs. BSC is frequently evaluated alongside other blockchain networks, including Ethereum, Solana, and Cardano, with respect to various parameters such as transaction velocity, scalability, fee structures, and community engagement @Gjorgjev2024Use. Binance Smart Chain (BSC) is recognized for its superior transaction speeds and reduced fees in comparison to Ethereum, rendering it a compelling alternative for decentralized applications (DApps) that necessitate a high volume of transactions with minimal user intervention @Gjorgjev2024Use.

Binance Smart Chain (BSC) operates on a dual-chain architecture that is designed to balance high performance with smart contract capabilities. This structure consists of two parallel blockchains—Binance Chain (BC) and Binance Smart Chain (BSC)—which function independently but are tightly coupled through a cross-chain communication mechanism as shown in @bsc. This design enables developers and users to benefit from both high-speed trading and flexible smart contract functionalities.

#figure(
  image("img/bsc.png", width: 80%),
  caption: [Binance Smart Chain Architecture]
)<bsc>

Binance Chain (BC) facilitates high-speed asset transfers and decentralized trading but does not support complex smart contracts. Binance Smart Chain (BSC). The two chains communicate through cross-chain modules using BSC and oracle relayers, enabling token transfers, staking, governance, and other interactions. This architecture balances performance and flexibility, making it suitable for applications like academic credential verification that require both scalability and cost efficiency.

Although Binance Smart Chain (BSC) provides advantages in terms of cost efficiency and transaction speed, these benefits are attained at the cost of a diminished degree of decentralization. In comparison to other blockchain platforms, such as Cardano and Polkadot, BSC exhibits a comparatively lower level of decentralization @Jia2022Measuring. This trade-off is deemed acceptable within the context of this research. The system places greater emphasis on efficiency, accessibility, and cost-effectiveness rather than on achieving maximal decentralization. The primary objective is to establish a verifiable, tamper-resistant, and scalable platform for the credentialing of academic qualifications.

It is important to highlight that the Binance Smart Chain (BSC) has functioned as a platform for a range of token-related activities, several of which have elicited ethical considerations, including phenomena such as "rug pulls" and the utilization of high-frequency trading algorithms, exemplified by sniper bots @Cernera2022Token. These challenges reveal specific vulnerabilities within the Binance Smart Chain (BSC) ecosystem. Nevertheless, when considering non-financial assets such as diploma credentials—where speculative trading is absent—the potential for exploitation is considerably diminished. Additionally, the implementation of comprehensive smart contract audits can further alleviate these risks.

The decision to utilize Binance Smart Chain (BSC) for this research is primarily influenced by its capacity to deliver high transaction throughput and cost efficiency—qualities that are critical for a diploma verification system, which is likely to involve numerous on-chain interactions.

A notable advantage of Binance Smart Chain (BSC) lies in its compatibility with the Ethereum Virtual Machine (EVM), enabling developers to leverage existing Ethereum-based smart contracts and tools. This interoperability not only accelerates development but also promotes adherence to established standards for credential issuance and verifications @2024CrossBlockchain. This compatibility not only expedites the development process but also enhances the incorporation of widely recognized standards for the issuance and verification of credentials.

